title: Brenden Gray
description: Mathematics student and researcher at VIU
baseurl: ""
url: "https://brendengray.ca"

#theme: cvless

# site settings
taglong: Undergraduate mathematics student/tutor, aspiring graph theorist
cv: true

# author settings
author:
  name: Brenden Gray
  email: brenden1104@gmail.com
photo: assets/images/IMG1.jpg  # optional, remove if you don't have a photo

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
