title: Brenden Gray
description: Mathematics student and researcher at VIU
baseurl: ""
url: "https://brendengray.ca"

theme: cvless

# site settings
taglong: Undergraduate research in graph theory and pursuit-evasion games
tagshort: Mathematics Student
cv: true

# author settings
author:
  name: Brenden Gray
  email: brenden1104@gmail.com
photo: assets/files/photo.jpg  # optional, remove if you don't have a photo
joblines:
  - Vancouver Island University
  - BSc Mathematics, Expected June 2026
address: Nanaimo, BC, Canada
phone: ""  # You can add a number here or leave it blank

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
